### ISSUE TITLE
Please show images and videos in damus.io note display

### ISSUE THREAD

**Issue by kristapsk** [damus-io/website#20] opened 2024-03-14 01:42 UTC
See https://damus.io/note1lkyznsgxmyxqcnu97ayrwcx4hdvxv9806d8yw4cj37rx6z74sj4sc6asp6, for example. It currently looks like this:

![image](https://github.com/damus-io/website/assets/4500994/af6df6d3-9acf-4e9b-920c-aad463c1cb94)

Would be a lot cooler to show image, not link, as Damus app itself does.

Problem is that it is link offered by Damus when you want to share a note with someone, and usual workflow with pre-nostrers are following:

A: send him a link.
B: "what's that about? I don't get it!"
A: "if you click on the link there will be picture of actual meme. here's the pic."
B: "aaa, hahaha, LOL"

But just using share function from any social media app and then send it via Telegram, WhatsApp, whatever is social media experience users have used to.

**Comment by jb55** [comment] 2024-03-14 11:26
duplicate of https://github.com/damus-io/notecrumbs/issues/3

**Closed by jb55** 2024-03-14 11:26 UTC
